# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vgg16_visualization_layout.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.console_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.console_output.setObjectName("console_output")
        self.horizontalLayout_3.addWidget(self.console_output)
        self.console_output2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.console_output2.setObjectName("console_output2")
        self.horizontalLayout_3.addWidget(self.console_output2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.layerNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.layerNumber.setMinimum(0)
        self.layerNumber.setMaximum(200)
        self.layerNumber.setObjectName("layerNumber")
        self.horizontalLayout_2.addWidget(self.layerNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.featureMapNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.featureMapNumber.setMaximum(600)
        self.featureMapNumber.setObjectName("featureMapNumber")
        self.horizontalLayout_5.addWidget(self.featureMapNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layerButton = QtWidgets.QPushButton(self.centralwidget)
        self.layerButton.setObjectName("layerButton")
        self.verticalLayout_4.addWidget(self.layerButton)
        self.outputFeatureMaps = QtWidgets.QPushButton(self.centralwidget)
        self.outputFeatureMaps.setObjectName("outputFeatureMaps")
        self.verticalLayout_4.addWidget(self.outputFeatureMaps)
        self.specificFeatureMap = QtWidgets.QPushButton(self.centralwidget)
        self.specificFeatureMap.setObjectName("specificFeatureMap")
        self.verticalLayout_4.addWidget(self.specificFeatureMap)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.displayOutput = QtWidgets.QLabel(self.centralwidget)
        self.displayOutput.setObjectName("displayOutput")
        self.verticalLayout_2.addWidget(self.displayOutput)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadModel = QtWidgets.QPushButton(self.centralwidget)
        self.loadModel.setObjectName("loadModel")
        self.verticalLayout.addWidget(self.loadModel)
        self.modelSummary = QtWidgets.QPushButton(self.centralwidget)
        self.modelSummary.setObjectName("modelSummary")
        self.verticalLayout.addWidget(self.modelSummary)
        self.inputImage = QtWidgets.QPushButton(self.centralwidget)
        self.inputImage.setObjectName("inputImage")
        self.verticalLayout.addWidget(self.inputImage)
        self.computeOutput = QtWidgets.QPushButton(self.centralwidget)
        self.computeOutput.setObjectName("computeOutput")
        self.verticalLayout.addWidget(self.computeOutput)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.displayInput = QtWidgets.QLabel(self.centralwidget)
        self.displayInput.setAutoFillBackground(False)
        self.displayInput.setObjectName("displayInput")
        self.verticalLayout.addWidget(self.displayInput)
        self.displayPreprocessedInput = QtWidgets.QLabel(self.centralwidget)
        self.displayPreprocessedInput.setObjectName("displayPreprocessedInput")
        self.verticalLayout.addWidget(self.displayPreprocessedInput)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 2, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDuplicate_window = QtWidgets.QAction(MainWindow)
        self.actionDuplicate_window.setObjectName("actionDuplicate_window")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionDuplicate_window)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Layer Number"))
        self.label.setText(_translate("MainWindow", "Feature Map Number"))
        self.layerButton.setText(_translate("MainWindow", "Get Layer Configuration"))
        self.outputFeatureMaps.setText(_translate("MainWindow", "Show Output Feature Maps"))
        self.specificFeatureMap.setText(_translate("MainWindow", "Specific feature map"))
        self.displayOutput.setText(_translate("MainWindow", "TextLabel"))
        self.loadModel.setText(_translate("MainWindow", "Load Model"))
        self.modelSummary.setText(_translate("MainWindow", "MOdel Summary"))
        self.inputImage.setText(_translate("MainWindow", "Laod Input Image"))
        self.computeOutput.setText(_translate("MainWindow", "Predict Output"))
        self.displayInput.setText(_translate("MainWindow", "TextLabel"))
        self.displayPreprocessedInput.setText(_translate("MainWindow", "TextLabel"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionDuplicate_window.setText(_translate("MainWindow", "Duplicate window"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

